package com.deneme.influencerinsight.enums;

public enum OperationType {

    //CREATE OPERATIONS
    CREATE_ADMIN_USER,
    CREATE_CUSTOMER_USER,
    CREATE_SOCIAL_MEDIA_PLATFORM,
    CREATE_SOCIAL_MEDIA_VENDOR,

    //UPDATE OPERATIONS
    UPDATE_ADMIN_USER,
    UPDATE_CUSTOMER_USER,
    UPDATE_SOCIAL_MEDIA_PLATFORM,
    UPDATE_SOCIAL_MEDIA_VENDOR,

    //DEACTIVATE OPERATIONS
    DEACTIVATE_ADMIN_USER,
    DEACTIVATE_CUSTOMER_USER,
    DEACTIVATE_SOCIAL_MEDIA_PLATFORM,
    DEACTIVATE_SOCIAL_MEDIA_VENDOR


}
