server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/influencerdb
    username: dev
    password: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      enabled: true

openai:
  api:
    key: {OPENAI_API_KEY}
  base-url: https://api.openai.com/v1
