# ========== GENERAL ==========
server.port=8080
spring.application.name=influencer-insight

# ========== DATABASE ==========
spring.datasource.url=jdbc:postgresql://localhost:5432/influencerdb
spring.datasource.username=dev
spring.datasource.password=dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ========== MAIL CONFIG ==========
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=***
spring.mail.password=***
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

# ========== OPENAI ==========
openai.api.key=***
openai.base-url=https://api.openai.com/v1
openai.model=gpt-4o-mini

# ========== SWAGGER ==========
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ========== LOGGING ==========
logging.level.com.deneme.influencerinsight=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# ========== JWT ==========
jwt.secret=RkFLRV9TRUNSRVRfS0VZX1RPS19CRV9SRUxBQ0VEX1NFQ1VSRQ==
jwt.refresh.token.expiry=604800
jwt.access-token.expiration-ms=900000
jwt.refresh-token.expiration-ms=604800000

# ========== Google OAuth (Youtube) ==========
google.youtube.client-id=***
google.youtube.client-secret=***
google.youtube.redirect-uri=http://localhost:8080/api/youtube/oauth/callback
google.youtube.scopes=https://www.googleapis.com/auth/youtube.readonly,https://www.googleapis.com/auth/yt-analytics.readonly

# ========== Instagram / Facebook OAuth ==========
instagram.client-id=***
instagram.client-secret=***
instagram.redirect-uri=http://localhost:8080/api/instagram/oauth/callback
instagram.scopes=public_profile,instagram_basic,instagram_manage_insights,pages_read_engagement,pages_show_list,instagram_manage_comments

# ========== TIKTOK ==========
tiktok.client-key=***
tiktok.client-secret=***
tiktok.base-url=https://open.tiktokapis.com
tiktok.auth-base-url=https://www.tiktok.com
tiktok.redirect-uri=http://localhost:8080/api/tiktok/oauth/callback
tiktok.tokenRefreshWindowMinutes=0
tiktok.scopes=user.info.basic,user.info.profile,video.list,video.upload,video.publish
