CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_type VARCHAR(64) NOT NULL UNIQUE,
    create_user_id BIGINT,
    update_user_id BIGINT,
    create_date TIMESTAMP NOT NULL,
    update_date TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL,
    role_id BIGINT NOT NULL REFERENCES role(id),
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    account_status VARCHAR(32) NOT NULL DEFAULT 'PENDING_VERIFICATION',
    verification_token VARCHAR(255),
    verification_token_expires_at TIMESTAMP WITH TIME ZONE,
    create_user_id BIGINT,
    update_user_id BIGINT,
    create_date TIMESTAMP NOT NULL,
    update_date TIMESTAMP
);

CREATE TABLE IF NOT EXISTS social_media_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform VARCHAR(32) NOT NULL,
    username VARCHAR(255) NOT NULL,
    profile_url VARCHAR(2048),
    access_token TEXT,
    refresh_token TEXT,
    token_expires_at TIMESTAMP WITH TIME ZONE,
    external_id VARCHAR(255),
    extra_data TEXT,
    last_synced_at TIMESTAMP WITH TIME ZONE,
    user_id BIGINT NOT NULL REFERENCES users(id),
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(64) NOT NULL UNIQUE,
    expiry_date TIMESTAMP WITH TIME ZONE NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id),
    create_user_id BIGINT,
    update_user_id BIGINT,
    create_date TIMESTAMP NOT NULL,
    update_date TIMESTAMP
);

CREATE TABLE IF NOT EXISTS oauth_state (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state VARCHAR(128) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES users(id),
    platform VARCHAR(32) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS token_blacklist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(64) NOT NULL UNIQUE,
    expiration_date TIMESTAMP NOT NULL,
    create_user_id BIGINT,
    update_user_id BIGINT,
    create_date TIMESTAMP NOT NULL,
    update_date TIMESTAMP
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS account_status VARCHAR(32);
UPDATE users
SET account_status = CASE WHEN email_verified THEN 'ACTIVE' ELSE 'PENDING_VERIFICATION' END
WHERE account_status IS NULL;
ALTER TABLE users ALTER COLUMN account_status SET NOT NULL;
ALTER TABLE users ALTER COLUMN username SET NOT NULL;
ALTER TABLE users ALTER COLUMN email SET NOT NULL;
ALTER TABLE users ALTER COLUMN password SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_users_username ON users (username);
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_email_lower ON users (LOWER(email));

ALTER TABLE social_media_account ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE social_media_account ALTER COLUMN access_token TYPE TEXT;
ALTER TABLE social_media_account ALTER COLUMN refresh_token TYPE TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS ux_social_account_owner_platform_external
    ON social_media_account (user_id, platform, external_id)
    WHERE external_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_social_account_owner_platform_username
    ON social_media_account (user_id, platform, username);
CREATE INDEX IF NOT EXISTS idx_social_account_user_platform ON social_media_account (user_id, platform);
CREATE INDEX IF NOT EXISTS idx_social_account_external_id ON social_media_account (external_id);

ALTER TABLE oauth_state ADD COLUMN IF NOT EXISTS user_id BIGINT;
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'oauth_state' AND column_name = 'username'
    ) THEN
        EXECUTE '
            UPDATE oauth_state state
            SET user_id = users.id
            FROM users
            WHERE users.username = state.username
              AND state.user_id IS NULL';
    END IF;
END $$;
DELETE FROM oauth_state WHERE user_id IS NULL;
ALTER TABLE oauth_state ALTER COLUMN user_id SET NOT NULL;
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_oauth_state_user') THEN
        ALTER TABLE oauth_state
            ADD CONSTRAINT fk_oauth_state_user FOREIGN KEY (user_id) REFERENCES users(id);
    END IF;
END $$;
ALTER TABLE oauth_state DROP COLUMN IF EXISTS username;
CREATE INDEX IF NOT EXISTS idx_oauth_state_expires_at ON oauth_state (expires_at);

UPDATE token_blacklist
SET token = rtrim(translate(encode(digest(token, 'sha256'), 'base64'), '+/', '-_'), '=')
WHERE length(token) > 64;
ALTER TABLE token_blacklist ALTER COLUMN token TYPE VARCHAR(64);
CREATE INDEX IF NOT EXISTS idx_blacklist_expiration ON token_blacklist (expiration_date);

CREATE TABLE IF NOT EXISTS social_media_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES social_media_account(id),
    collected_at TIMESTAMP WITH TIME ZONE NOT NULL,
    payload JSONB NOT NULL,
    schema_version INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS idx_social_snapshot_account_collected
    ON social_media_snapshot (account_id, collected_at);
